wordpress:
  wordpressPassword: foo
  mariadb:
    db:
      password: bar
    rootUser:
      password: baz
  ingress:
    enabled: true
    certManager: true
    hostname: wp.hashcorp-voatsap.cluster.dev
    annotations: {
      kubernetes.io/ingress.class: nginx,
      cert-manager.io/cluster-issuer: letsencrypt-prod
    }
    extraTls:
    - hosts:
      - wp.hashcorp-voatsap.cluster.dev
      secretName: wp.hashcorp-voatsap.cluster.dev
