on:
  push:
    paths:
      - '.github/workflows/**' # Trigger updates on Workflow changes
      - '.cluster.dev/**' # Path to cluster declaration manifests
      - '/kubernetes/apps/**' # ArgoCD application directories
    branches:
      - master
jobs:
  deploy_cluster_job:
    env:
      VERBOSE_LVL: DEBUG
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
    runs-on: ubuntu-latest
    name: Create and Update Kubernetes Clusters
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@feature/GH-56
    - name: Get the Cluster Credentials
      run: echo -e "\n\033[1;32m${{ steps.reconcile.outputs.ssh }}\n\033[1;32m${{ steps.reconcile.outputs.kubeconfig }}\n\033[1;32m${{ steps.reconcile.outputs.argocd }}"

