on:
  push:
    paths:
      - '.github/workflows/**' # Trigger updates on Workflow changes
      - '.cluster.dev/**' # Path to cluster declaration manifests
      - '/kubernetes/apps/**' # ArgoCD application directories
    branches:
      - master
jobs:
  deploy_cluster_job:
    runs-on: ubuntu-latest
    name: Create and Update Kubernetes Clusters
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout Repo
      uses: actions/checkout@v2
    # - uses: ./ # Uses an action in the root directory
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@feature/GH-56
      #uses: shalb/cluster.dev@master
      with:
        cluster-config: './.cluster.dev/'
        cloud-user: ${{ secrets.aws_access_key_id }}
        cloud-pass: ${{ secrets.aws_secret_access_key }}
    # Use the output from the `reconcile` step
    - name: Get the Cluster Credentials
      run: echo -e "\n\033[1;32m${{ steps.reconcile.outputs.ssh }}\n\033[1;32m${{ steps.reconcile.outputs.kubeconfig }}\n\033[1;32m${{ steps.reconcile.outputs.argocd }}"
env:
  VERBOSE_LVL: DEBUG
